- name: Copy
  win_copy:
    src: C:/temp/test_1.csv
    dest: /tmp/test_1.csv
    force: yes
    remote_src: yes
    mode: 0755
  register: copy
  
  
- debug:
    var: copy
  
   

- name: Read CSV files
  read_csv:
    path: roles/role_check_csv_file/files/test_1.csv
  register: output
 

- name: check logic
  debug:
    msg: "{{ item['Phase Name'] }} is failed"
  with_items: "{{output.list}}"
  when: item["Number of phases Running"] == "1"



    



