# - name: Read CSV files
#   read_csv:
#     path: C:/temp/test_1.csv
#   register: output
#   delegate_to: 192.168.90.94

- name: Read CSV file
  slurp:
    src: C:/temp/test_1.csv
  register: output


- name: Show Output
  debug:
    msg: "{{ output['content'] | b64decode }}" 
    
- name: Result
  debug:
    msg: "Success"
  when: output.rc == 0
  
- name: Result
  debug:
    msg: "Failed"
  when: output.rc != 0  
