- name: Copy a file
  win_copy: 
   src: test_1.csv
   dest: C:\temp\test_1.csv
   force: yes
   mode: 0777
  register: copy
  
- debug:
    var: copy
  
   

- name: Read CSV files
  read_csv:
    path: roles/role_check_csv_file/files/test_1.csv
  register: output
 

- name: check logic
  debug:
    msg: "{{ item['Phase Name'] }} is failed"
  with_items: "{{output.list}}"
  when: item["Number of phases Running"] == "1"



    



