- name: Copy
  win_copy:
    src: test_1.csv
    dest: C:/temp/test_1.csv
   

- name: Read CSV files
  read_csv:
    path: roles/role_check_csv_file/files/test_1.csv 
    key: Phase Name
  register: output
  delegate_to: localhost




- name: Show Output
  debug:
    msg: "{{ output }}"
     
    



