# - name: Read CSV files
#   read_csv:
#     path: C:/temp/test_1.csv
#   register: output
#   delegate_to: 192.168.90.94

- name: Read CSV file
  slurp:
    src: C:/temp/test_1.csv
  register: output


- name: Show Output
  debug:
    msg: "{{ output['content'] | b64decode }}" 
    
- name: string found
  lineinfile:
    name: C:/temp/test_1.csv
    line: 'one'
    state: present
  check_mode: true
  register: conf
  failed_when: (conf is changed) or (conf is failed)
  
    
