- name: Copy
  win_copy:
    src: test_1.csv
    dest: C:/temp/test_1.csv
   



- name: Read CSV files
  read_csv:
    path: roles/role_check_csv_file/files/test_1.csv
    key: Number of phases Runnin
  register: output
  delegate_to: localhost

# - name: Read CSV file
#   slurp:
#     src: C:/temp/test_1.csv
#   register: output


- name: Show Output
  debug:
    msg: "{{ output }}"
#     var: "{{ item }}"
#   with_items: "{{ output['content'] | b64decode }}"
  #  msg: "{{ output['content'] | b64decode }}" 
    



