- name: Copy
  win_copy:
    src: C:/temp/test_1.csv
    dest: files/test_1.csv
    remote_src: yes
    mode: 0755
   

- name: Read CSV files
  read_csv:
    path: test_1.csv
  register: output
 

- name: check logic
  debug:
    msg: "{{item['Phase Name']}} is failed"
  with_items: "{{output.list}}"
  when: item['Number of phases Running'] == '1'



    



